close all
f = figure;


userP = uipanel(...
    'Title', 'User Data',...
    'Position',[.05 .60 .85 .35],...
    'FontSize',14 ...
);
userT = uitable(...
    userP,...
        'Units', 'normalized',...
    'Position', [0 0 1 1],...
    'Data', cell(5,1),...
    'ColumnWidth',{400}, ...
    'CellSelectionCallback',@cellSelection,...
    'FontSize',14 ...
);

%userT.RowName = {'path'};
userT.RowName = {};



userP2 = uipanel(...
    f,...
    'Title', '.',...
    'Position',[.85 .60 .10 .35],...
    'FontSize',14 ...
);
userT2 = uitable(...
    userP2,...
        'Units', 'normalized',...
    'Position', [0 0 1 1],...
    'Data', cell(5,1),...
    'ColumnWidth',{40}, ...
    'CellSelectionCallback',@cellSelection,...
    'RowName',{},...
    'FontSize',14 ...
);

userT.RowName = {'path'};








codeP = uipanel(...
    'Title', 'Program Data',...
    'Position',[.05 .05 .75 .55],...
    'FontSize',14 ...
);
codeT = uitable(...
    codeP,...
     'Units', 'normalized',...
    'Position', [0 0 1 1],...
    'Data', cell(20,1),...
    'ColumnWidth',{150} ...
);

function cellSelection(hObject,callbackdata)
     %numval = eval(callbackdata.EditData);
     %r = callbackdata.Indices(1)
     %c = callbackdata.Indices(2)
     %newdata = callbackdata.EditData
     %hObject.Data{r,c} = numval; 
     %disp(length(callbackdata.Indices))
     if length(callbackdata.Indices) == 2
        %disp(length(callbackdata.Indices))

         if callbackdata.Indices(1) == 1 && callbackdata.Indices(2) == 1
             hObject.Data(1,1) = {uigetdir()};
         end
     end
end
